# Generated by Django 5.0.7 on 2024-07-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={},
        ),
        migrations.AlterModelTable(
            name='counter',
            table=None,
        ),
    ]
