# Generated by Django 4.2.3 on 2024-07-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.TextField(blank=True, max_length=1024, verbose_name='图片url集'),
        ),
    ]
