# Generated by Django 5.0.7 on 2024-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='intorduction',
            new_name='introduction',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/', verbose_name='头像'),
        ),
    ]
