# Generated by Django 4.2.3 on 2024-07-22 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('cafeteria', '0002_alter_counter_options_alter_counter_table'),
        ('user', '0003_rename_intorduction_user_introduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_collections', to='post.post')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_collector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户帖子收藏',
                'verbose_name_plural': '用户帖子收藏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EatCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eat_collections', to='post.post')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eat_collector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户吃过收藏',
                'verbose_name_plural': '用户吃过收藏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounterCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_collections', to='cafeteria.counter')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_collector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户窗口收藏',
                'verbose_name_plural': '用户窗口收藏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CafeteriaCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_collections', to='cafeteria.cafeteria')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_collector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户食堂收藏',
                'verbose_name_plural': '用户食堂收藏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='cafeteria_collections',
            field=models.ManyToManyField(blank=True, related_name='收藏食堂列表', through='user.CafeteriaCollection', to='cafeteria.cafeteria'),
        ),
        migrations.AddField(
            model_name='user',
            name='counter_collections',
            field=models.ManyToManyField(blank=True, related_name='收藏窗口列表', through='user.CounterCollection', to='cafeteria.counter'),
        ),
        migrations.AddField(
            model_name='user',
            name='eat_collections',
            field=models.ManyToManyField(blank=True, related_name='吃过的食物列表', through='user.EatCollection', to='post.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='post_collections',
            field=models.ManyToManyField(blank=True, related_name='收藏帖子列表', through='user.PostCollection', to='post.post'),
        ),
    ]
